export const EVENT_TYPES = {
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_PAUSED: 'SESSION_PAUSED',
  SESSION_RESUMED: 'SESSION_RESUMED',
  SESSION_STOPPED: 'SESSION_STOPPED',
  SESSION_FAILED: 'SESSION_FAILED',

  PAGE_OPENED: 'PAGE_OPENED',
  PAGE_CLOSED: 'PAGE_CLOSED',
  POPUP_OPENED: 'POPUP_OPENED',
  DIALOG: 'DIALOG',
  NAVIGATION: 'NAVIGATION',

  POINTER_DOWN: 'POINTER_DOWN',
  CLICK: 'CLICK',
  INPUT_CHANGED: 'INPUT_CHANGED',
  FORM_SUBMITTED: 'FORM_SUBMITTED',
  KEY_ACTION: 'KEY_ACTION',

  DOM_MUTATION_SIGNAL: 'DOM_MUTATION_SIGNAL',

  SCREEN_STATE_CREATED: 'SCREEN_STATE_CREATED',
  SCREEN_STATE_CHANGED: 'SCREEN_STATE_CHANGED',

  SPEECH_STARTED: 'SPEECH_STARTED',
  TRANSCRIPT_PARTIAL: 'TRANSCRIPT_PARTIAL',
  TRANSCRIPT_FINAL: 'TRANSCRIPT_FINAL',

  SCREENSHOT_REQUESTED: 'SCREENSHOT_REQUESTED',
  SCREENSHOT_CAPTURED: 'SCREENSHOT_CAPTURED',

  RECORDER_ERROR: 'RECORDER_ERROR',
  TRANSCRIPTION_OFFLINE: 'TRANSCRIPTION_OFFLINE',
  TRANSCRIPTION_ONLINE: 'TRANSCRIPTION_ONLINE',
  MICROPHONE_DISCONNECTED: 'MICROPHONE_DISCONNECTED',
  BROWSER_CRASHED: 'BROWSER_CRASHED',
} as const;

export type EventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];
